spring:
  profiles:
    include: db
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration
    validate-on-migrate: true

mybatis:
  type-aliases-package: com.uts.pojo